uv run src/run.py --country-code ASM
uv run src/run.py --country-code COK
uv run src/run.py --country-code FJI
uv run src/run.py --country-code PYF
uv run src/run.py --country-code GUM
uv run src/run.py --country-code KIR
uv run src/run.py --country-code MHL
uv run src/run.py --country-code FSM
uv run src/run.py --country-code NRU
uv run src/run.py --country-code NCL
uv run src/run.py --country-code NIU
uv run src/run.py --country-code MNP
uv run src/run.py --country-code PLW
uv run src/run.py --country-code PNG
uv run src/run.py --country-code PCN
uv run src/run.py --country-code SLB
uv run src/run.py --country-code WSM
uv run src/run.py --country-code TKL
uv run src/run.py --country-code TON
uv run src/run.py --country-code TUV
uv run src/run.py --country-code VUT
uv run src/run.py --country-code WLF